# Generated by Django 4.1.6 on 2023-02-23 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_like', to='podcast.podcast'),
        ),
    ]
