# Generated by Django 4.1.6 on 2023-02-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_alter_like_music'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
